# Generated by Django 4.0.1 on 2022-01-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_crud_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='', max_length=255),
        ),
    ]
